/**
 * Builds the registry artifacts.
 *
 * Ported from `evilcharts/src/scripts/build-registry.mts`, which produces the same three things:
 *
 *   1. `src/lib/registry/__index__.ts` — the generated item index the docs read
 *   2. root `registry.json` — the shadcn registry manifest
 *   3. `static/r/<name>.json` — one registry-item file per item, with the sources inlined
 *
 * The Svelte registry builder intentionally differs from the reference in two ways:
 *
 * - The reference shells out to `shadcn build` for step 3. The Svelte port writes the equivalent
 *   `registry-item.json` payload directly and performs the two transformations the CLI normally
 *   handles: local registry dependencies become relative item URLs, and authoring imports become
 *   their consumer paths.
 * - A `files[].path` that names a **directory** is expanded into one entry per source file inside
 *   it, sorted, with tests skipped. A Svelte chart is a folder rather than a single `.tsx`.
 *
 * Run with `pnpm registry:build`.
 */
import { mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { registry } from '../src/lib/registry/index.js';
import {
	REGISTRY_ITEM_SCHEMA,
	REGISTRY_SCHEMA,
	type RegistryItem,
	type RegistryItemFile
} from '../src/lib/registry/schema.js';

const ROOT = process.cwd();
const REGISTRY_DIR = path.join(ROOT, 'src/lib/registry');
const INDEX_FILE = path.join(REGISTRY_DIR, '__index__.ts');
const REGISTRY_JSON = path.join(ROOT, 'registry.json');
const ITEMS_DIR = path.join(ROOT, 'static/r');

/** Sources only: specs, e2e suites, harnesses and snapshots are not part of an installable item. */
function isSource(file: string) {
	return (
		/\.(svelte|ts)$/.test(file) &&
		!/\.spec\.(ts|svelte)$/.test(file) &&
		!/\.e2e\.ts$/.test(file) &&
		!file.endsWith('.snap')
	);
}

/** Every source file under `dir`, relative to it, sorted so the output is deterministic. */
async function sourcesIn(dir: string): Promise<string[]> {
	const entries = await readdir(dir, { withFileTypes: true });
	const found: string[] = [];
	for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
		if (entry.name === '__snapshots__') continue;
		if (entry.isDirectory()) {
			found.push(...(await sourcesIn(path.join(dir, entry.name))).map((f) => `${entry.name}/${f}`));
		} else if (isSource(entry.name)) {
			found.push(entry.name);
		}
	}
	return found;
}

/** Resolves one authored file entry into the concrete files it stands for. */
async function expand(file: RegistryItemFile): Promise<RegistryItemFile[]> {
	const absolute = path.join(REGISTRY_DIR, file.path);
	const info = await stat(absolute);
	if (!info.isDirectory()) return [file];

	return (await sourcesIn(absolute)).map((name) => ({
		...file,
		path: `${file.path}/${name}`,
		target: file.target ? `${file.target}/${name}` : undefined
	}));
}

async function expandedItems(): Promise<RegistryItem[]> {
	return Promise.all(
		registry.items.map(async (item) => ({
			...item,
			files: (await Promise.all(item.files.map(expand))).flat()
		}))
	);
}

/**
 * The generated item index.
 *
 * The reference emits `React.lazy(() => import(...))` per item because Next cannot discover
 * modules by glob; Vite can, so the live component lookup lives in the hand-written
 * `components.ts` and this file carries only the metadata and file lists that the registry, the
 * docs source viewer and the agent surfaces read.
 */
async function buildIndex(items: RegistryItem[]) {
	const body = items
		.map(
			(item) => `\t'${item.name}': {
\t\tname: '${item.name}',
\t\tdescription: ${JSON.stringify(item.description ?? '')},
\t\ttype: '${item.type}',
\t\tregistryDependencies: ${JSON.stringify(item.registryDependencies ?? [])},
\t\tdependencies: ${JSON.stringify(item.dependencies ?? [])},
\t\tfiles: ${JSON.stringify(item.files)}
\t}`
		)
		.join(',\n');

	const source = `// This file is autogenerated by scripts/build-registry.ts.
// Do not edit it directly — run \`pnpm registry:build\`.
import type { RegistryItem } from './schema.js';

export const Index: Record<string, RegistryItem> = {
${body}
};
`;
	await rm(INDEX_FILE, { force: true });
	await writeFile(INDEX_FILE, source);
}

/** The root manifest, with every path made relative to the repository. */
async function buildRegistryJson(items: RegistryItem[]) {
	const manifest = {
		$schema: REGISTRY_SCHEMA,
		...registry,
		items: items.map((item) => ({
			...item,
			files: item.files.map((file) => ({ ...file, path: `src/lib/registry/${file.path}` }))
		}))
	};
	await rm(REGISTRY_JSON, { force: true });
	await writeFile(REGISTRY_JSON, JSON.stringify(manifest, null, 2) + '\n');
}

/** Convert the authoring paths used by the docs site into the paths installed in a consumer. */
function consumerSource(source: string): string {
	return source
		.replaceAll('$lib/registry/charts/', '$lib/components/evilcharts/charts/')
		.replaceAll('$lib/registry/ui/', '$lib/components/evilcharts/ui/')
		.replaceAll('$lib/registry/blocks/', '$lib/components/evilcharts/blocks/')
		.replace(/(['"])\.\.\/\.\.\/charts\//g, '$1$lib/components/evilcharts/charts/')
		.replace(/(['"])\.\.\/\.\.\/ui\//g, '$1$lib/components/evilcharts/ui/')
		.replace(/(from\s+['"]\.\/)b-/g, '$1');
}

/** `@evilcharts/name` is an authoring shorthand; published items use supported relative URLs. */
function consumerDependencies(dependencies: string[] | undefined): string[] {
	return (dependencies ?? []).map((dependency) =>
		dependency.startsWith('@evilcharts/')
			? `./${dependency.slice('@evilcharts/'.length)}.json`
			: dependency
	);
}

/** One installable item file per entry, with consumer-ready source inlined. */
async function buildItemFiles(items: RegistryItem[]) {
	await mkdir(ITEMS_DIR, { recursive: true });
	for (const item of items) {
		const files = await Promise.all(
			item.files.map(async (file) => ({
				path: `src/lib/registry/${file.path}`,
				content: consumerSource(await readFile(path.join(REGISTRY_DIR, file.path), 'utf8')),
				type: file.type,
				...(file.target ? { target: file.target } : {})
			}))
		);
		const registryDependencies = consumerDependencies(item.registryDependencies);
		await writeFile(
			path.join(ITEMS_DIR, `${item.name}.json`),
			JSON.stringify(
				{ $schema: REGISTRY_ITEM_SCHEMA, ...item, registryDependencies, files },
				null,
				2
			) + '\n'
		);
	}
	// The reference also publishes the whole manifest under the same directory.
	await writeFile(path.join(ITEMS_DIR, 'registry.json'), await readFile(REGISTRY_JSON, 'utf8'));
}

const items = await expandedItems();
const fileCount = items.reduce((total, item) => total + item.files.length, 0);

console.log(`└ ${items.length} items, ${fileCount} files`);
console.log('└ Building src/lib/registry/__index__.ts...');
await buildIndex(items);
console.log('└ Building registry.json...');
await buildRegistryJson(items);
console.log('└ Building static/r...');
await buildItemFiles(items);
console.log('└ Registry build completed successfully!');
